# Generated by Django 4.2 on 2025-05-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('time_start', models.TimeField(verbose_name='Время начала')),
                ('time_end', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Meetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата митапа')),
                ('start_meetup', models.TimeField(verbose_name='Время начала мероприятия')),
                ('end_meetup', models.TimeField(verbose_name='Время конца мероприятия')),
                ('location', models.CharField(max_length=150, verbose_name='Локация мероприятия')),
            ],
            options={
                'verbose_name': 'Митап',
                'verbose_name_plural': 'Митапы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=60, unique=True, verbose_name='Телеграм id')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('role', models.CharField(choices=[('speaker', 'Докладчик'), ('listener', 'Слушатель')], default='listener', max_length=10, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to='meetapp.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, verbose_name='Текст вопроса')),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetapp.user', verbose_name='Спрашивающий')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetapp.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='meetup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetapp.meetup', verbose_name='Событие'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meetapp.speaker', verbose_name='Спикеры'),
        ),
    ]
