# Generated by Django 4.2 on 2025-05-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=300, verbose_name='Анкета о себе'),
        ),
    ]
