# Generated by Django 4.2 on 2025-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0002_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Время появления вопроса'),
        ),
    ]
