# Generated by Django 4.2 on 2025-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0003_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время появления вопроса'),
        ),
    ]
