# Generated by Django 4.2 on 2025-05-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0004_alter_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Никнейм'),
        ),
    ]
