# Generated by Django 4.2 on 2025-05-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0005_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='Подписан на уведомления о будущих мероприятиях'),
        ),
    ]
