# Generated by Django 4.2 on 2025-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0006_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст вопроса'),
        ),
    ]
