# Generated by Django 4.2 on 2025-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0006_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Организатор (может делать рассылки)'),
        ),
    ]
