# Generated by Django 4.2 on 2025-05-25 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0007_alter_application_text'),
        ('meetapp', '0007_user_is_admin'),
    ]

    operations = [
    ]
