# Generated by Django 4.2 on 2025-05-26 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0008_merge_0007_alter_application_text_0007_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст заявки'),
        ),
        migrations.CreateModel(
            name='DonationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Сумма доната в рублях')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время доната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='meetapp.user', verbose_name='Пользователь, который задонатил')),
            ],
        ),
    ]
