# Generated by Django 4.2 on 2025-05-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetapp', '0009_alter_application_text_donationmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationmessage',
            options={'ordering': ['-time'], 'verbose_name': 'Сообщение о донате', 'verbose_name_plural': 'Сообщения о донатах'},
        ),
    ]
